### ISSUE TITLE
When i want to upload i get this error message: esptool.FatalError: Invalid head of packet (0x46) (Silicon Labs CP210x USB to UART brige )

### ISSUE THREAD

**Issue by Rokim1** [ramapcsx2/gbs-control#252]
Hi when i compile no problem when i want to upload i get this error.
i used all the setting from https://github.com/ramapcsx2/gbs-control/wiki/Software-Setup
i hope som body can help me 

Arduino:1.8.15 (Windows Store 1.8.49.0) (Windows 10), Board:"LOLIN(WEMOS) D1 R2 & mini, 160 MHz, Flash, Legacy (new can return nullptr), All SSL ciphers (most compatible), 4MB (FS:1MB OTA:~1019KB), v2 Lower Memory, Disabled, None, Only Sketch, 921600"

Executable segment sizes:

IROM   : 674708          - code in flash         (default or ICACHE_FLASH_ATTR) 

IRAM   : 29952   / 32768 - code in IRAM          (ICACHE_RAM_ATTR, ISRs...) 

DATA   : 2348  )         - initialized variables (global, static) in RAM/HEAP 

RODATA : 5184  ) / 81920 - constants             (global, static) in RAM/HEAP 

BSS    : 28360 )         - zeroed variables      (global, static) in RAM/HEAP 

De schets gebruikt 712192 bytes (68%)  programma-opslagruimte. Maximum is 1044464 bytes.

Globale variabelen gebruiken 35892 bytes (43%) van het dynamisch geheugen. Resteren 46028 bytes voor lokale variabelen. Maximum is 81920 bytes.

esptool.py v2.8

Serial port COM7

Connecting........__

Chip is ESP8266EX

Features: WiFi

WARNING: Detected crystal freq 20.39MHz is quite different to normalized freq 26MHz. Unsupported crystal in use?

Crystal is 26MHz

MAC: 00:08:ff:00:00:00

Uploading stub...

Running stub...

Traceback (most recent call last):

  File "C:\Users\Robin Game PC\Documents\ArduinoData\packages\esp8266\hardware\esp8266\2.6.3/tools/upload.py", line 65, in <module>

    esptool.main(cmdline)

  File "C:/Users/Robin Game PC/Documents/ArduinoData/packages/esp8266/hardware/esp8266/2.6.3/tools/esptool\esptool.py", line 2909, in main

    esp = esp.run_stub()

  File "C:/Users/Robin Game PC/Documents/ArduinoData/packages/esp8266/hardware/esp8266/2.6.3/tools/esptool\esptool.py", line 637, in run_stub

    p = self.read()

  File "C:/Users/Robin Game PC/Documents/ArduinoData/packages/esp8266/hardware/esp8266/2.6.3/tools/esptool\esptool.py", line 292, in read

    return next(self._slip_reader)

  File "C:/Users/Robin Game PC/Documents/ArduinoData/packages/esp8266/hardware/esp8266/2.6.3/tools/esptool\esptool.py", line 2057, in slip_reader

    raise FatalError('Invalid head of packet (0x%s)' % hexify(b))

esptool.FatalError: Invalid head of packet (0x46)

esptool.FatalError: Invalid head of packet (0x46)

Dit rapport zou meer informatie bevatten met
"Uitgebreide uitvoer weergeven tijden compilatie"
optie aan in Bestand -> Voorkeuren.

**Comment by Rokim1** [comment]
Problem found used a ESP32
